---
- hosts: "{{hosts}}"
become: true
tasks:
- name: create user
  user:
    name: "{{item}}"
    shell: "/bin/bash"
    comment: "user created by ANSIBLE"
    state: present
  with_items:
    - oracle
    