---
- hosts: "{{hosts}}"
  become: true
  tasks: 
    - name: install package httpd
      package:
        name: httpd
        state: latest
    - name: start package & enable it
      service:
        name: httpd
        state: started
        enabled: yes
    - name: initial welcome page
      file:
        path: /var/www/html/index.html
        state: touch
        # state: absent
    - name: add something
      copy:
        content: "Alls well that ends well"
        dest: /var/www/html/index.html

      
